name: CI
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - docker build -t ci .
            - docker container run -d -p 3000:3000 --name ci ci
            - docker container exec ci yarn test 